import Head from "next/head";
import Button from "react-bootstrap/Button";
import Form from "react-bootstrap/Form";
import Lottie from "lottie-react";
import loginAnimation from "../../anim/login-leady.json";
import Link from "next/link";
const style = {
  height: 400,
};

const login = () => {
  return (
    <>
      <Head>
        <title>Login Now</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="container py-5 my-5">
        <section className="row row-cols-lg-2">
          <Form className="shadow p-4 rounded">
            <div className="mb-5">
              <h3 className="blue-header">Login Now</h3>
              <span>New here? </span>
              <Link href={"/authentication/Register"}>
                Register now
              </Link>
            </div>
            <Form.Group className="mb-3" controlId="formBasicEmail">
              <Form.Label>Email address</Form.Label>
              <Form.Control type="email" placeholder="Enter email" />
              <Form.Text className="text-muted">
                We'll never share your email with anyone else.
              </Form.Text>
            </Form.Group>

            <Form.Group className="mb-3" controlId="formBasicPassword">
              <Form.Label>Password</Form.Label>
              <Form.Control type="password" placeholder="Password" />
              <Form.Text className="text-muted">Forget password?</Form.Text>
            </Form.Group>
            <Button className="blue-header" type="submit">
              Login Now
            </Button>
          </Form>
          <div>
            <Lottie animationData={loginAnimation} style={style} />
          </div>
        </section>
      </section>
    </>
  );
};

export default login;
