import Head from "next/head";
import Button from "react-bootstrap/Button";
import Form from "react-bootstrap/Form";
import Lottie from "lottie-react";
import loginAnimation from "../../anim/form-registration.json";
import Link from "next/link";
const style = {
  height: 400,
};

const Register = () => {
  return (
    <>
      <Head>
        <title>Registration Now</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="container py-5 my-5">
        <section className="row row-cols-lg-2">
          <Form className="shadow p-4 rounded">
            <div className="mb-5">
              <h3 className="blue-header">Create a new account</h3>
              <span>Already registered? </span>
              <Link href={"/authentication/Login"}>Login now</Link>
            </div>
            <div className="row row-cols-2">
              <Form.Group className="mb-3" controlId="formBasicFirstName">
                <Form.Label>First Name</Form.Label>
                <Form.Control type="text" placeholder="Enter first name" />
              </Form.Group>
              <Form.Group className="mb-3" controlId="formBasicLastName">
                <Form.Label>Last Name</Form.Label>
                <Form.Control type="text" placeholder="Enter last name" />
              </Form.Group>
              <Form.Group className="mb-3" controlId="formBasicPhoneNumber">
                <Form.Label>Phone Number</Form.Label>
                <Form.Control type="number" placeholder="Enter phone number" />
              </Form.Group>
              <Form.Group className="mb-3" controlId="formBasicEmail">
                <Form.Label>Email address</Form.Label>
                <Form.Control type="email" placeholder="Enter email" />
              </Form.Group>

              <Form.Group className="mb-3" controlId="formBasicPassword">
                <Form.Label>Password</Form.Label>
                <Form.Control type="password" placeholder="Password" />
              </Form.Group>

              <Form.Group className="mb-3" controlId="formBasicConfirmPassword">
                <Form.Label>Confirm Password</Form.Label>
                <Form.Control type="password" placeholder="Confirm Password" />
              </Form.Group>
            </div>

            <Button className="blue-header" type="submit">
              Register Now
            </Button>
          </Form>
          <div>
            <Lottie animationData={loginAnimation} style={style} />
          </div>
        </section>
      </section>
    </>
  );
};

export default Register;
