import AboutUs from "@/components/Home/AboutUs";
import ClientTestimonials from "@/components/Home/ClientTestimonials";
import ExploreUs from "@/components/Home/ExploreUs";
import HowItWorks from "@/components/Home/HowItWorks";
import Landing from "@/components/Home/Landing";
import Rightbar from "@/components/Home/Rightbar";
import WhyChooseUs from "@/components/Home/WhyChooseUs";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Papaya Coders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <Landing />
        <section className="row py-5">
          <div className="col-12 col-lg-7">
            <AboutUs />
            <ExploreUs/>
          </div>
          <div className="col-12 col-lg-5">
            <Rightbar />
          </div>
        </section>
        <WhyChooseUs/>
        <HowItWorks/>
        <ClientTestimonials/>
      </main>
    </>
  );
}
