import ExploreUs from "@/components/Home/ExploreUs";
import Head from "next/head";
import React from "react";
import { Typewriter } from "react-simple-typewriter";
import SatisfiedClient from "./SatisfiedClient";

const AboutUs = () => {
  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <div className="hero">
          <div className="hero-mask h-100">
            <div className="text-white text-center hero-content h-100 container d-flex flex-column align-items-center justify-content-center">
              <h2 className="blue-title display-4 fw-bold">
                <Typewriter
                  words={[
                    "Welcome to Edits From India",
                    "Premium Quality Edits",
                  ]}
                  loop={""}
                  cursor
                  cursorStyle="|"
                  typeSpeed={70}
                  deleteSpeed={50}
                  delaySpeed={2000}
                />
              </h2>
              <h4 className="my-4">
                You Shoot We Edit into timeless masterpieces with Edits from
                India - The video editing , photo and Album designing service
                provider exceptional results in each project.
              </h4>
              <button className="explore-now fw-bold">Explore Now</button>
            </div>
          </div>
        </div>
        <div className="container py-5">
          <div className="row">
            <div className="col">
              <h4 className="blue-header">About Us</h4>
              <p className="content">
                Edits from India is the one stop destination for anything and
                everything in photography editing services. Delivering a awesome
                service is not a work of single man, it’s a team work of
                professional people. We have quality professional photographers,
                editors and we have all latest tools related to editing.
              </p>
            </div>
            <div className="col">
              <img
                className="img-fluid"
                src="https://admin.editsfromindia.com/storage/aboutus/aboutus-63f315da38576.jpg"
                alt=""
              />
            </div>
          </div>
          <div className="row my-5">
            <div className="col">
              <img
                className="img-fluid"
                src="https://admin.editsfromindia.com/storage/aboutus/aboutus-63f315dab1e79.jpg"
                alt=""
              />
            </div>
            <div className="col">
              <h4 className="blue-header">Who are we?</h4>
              <p className="content">
                Heave the level of your photographs with full-cycle photo
                editing services from Edits from India. As a leading photo
                editing service provider in India, we combine creativity with
                advanced technologies to create extraordinary results
                personalized to your requirements and choices. <br />
                We have been working for our client’s satisfaction with our
                quality Photoshop Editing Services. Our image editing and
                retouching professionals are expert in editing, clipping path,
                product photo editing service, restoration, Drop Shadow, Ghost
                Mannequin All of our client can vouch for us when it comes to
                our impressive turn around time. We provide all of our services
                to our clients at cost effective rates.
              </p>
            </div>
          </div>
          <ExploreUs/>
          <SatisfiedClient/>
        </div>
      </section>
    </>
  );
};

export default AboutUs;
