import Head from "next/head";
import Tab from "react-bootstrap/Tab";
import Tabs from "react-bootstrap/Tabs";
import Carousel from "react-multi-carousel";
import "react-multi-carousel/lib/styles.css";

const photoEditingCards = [
  {
    name: "Background Removal",
    img: "https://admin.editsfromindia.com/storage/portfolios/portfolios-63dc8de08122c.jpg",
  },
  {
    name: "Photo Reducing",
    img: "https://admin.editsfromindia.com/storage/portfolios/portfolios-63dc9036961ac.jpg",
  },
  {
    name: "Cliping Path",
    img: "https://admin.editsfromindia.com/storage/portfolios/portfolios-63dc8ec8b3a98.jpg",
  },
  {
    name: "Image Masking",
    img: "https://admin.editsfromindia.com/storage/portfolios/portfolios-63dc8f7b95035.jpg",
  },
  {
    name: "Drop Shadow",
    img: "https://admin.editsfromindia.com/storage/portfolios/portfolios-63dc8f184ba3d.jpg",
  },
];

const responsive = {
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: 3,
      slidesToSlide: 3,
    },
    tablet: {
      breakpoint: { max: 1024, min: 464 },
      items: 2,
      slidesToSlide: 2,
    },
    mobile: {
      breakpoint: { max: 464, min: 0 },
      items: 1,
      slidesToSlide: 1,
    },
  };
  const videoEditingCards = [
    {
      name: "Background Removal",
      img: "https://cdn-site-assets.veed.io/How_to_edit_MP_4_Videos_ebdc2c6343/How_to_edit_MP_4_Videos_ebdc2c6343.png?width=1536&quality=75",
    },
    {
      name: "Capturing WOW",
      img: "https://yt3.googleusercontent.com/ytc/AL5GRJVICGWu47-99CayDpTcY5IdpWHjtSxAVhHwmZ9S=s900-c-k-c0x00ffffff-no-rj",
    },
    {
      name: "Vimeo Video",
      img: "https://www.lifewire.com/thmb/PhW9E-5EXgBkEiKUwiXrIM5qsw4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/vimeo-5ae0e7a2fa6bcc0036691998.jpg",
    },
  ];
  const aldumEditingCards = [
    {
      name: "Model Album",
      img: "https://admin.editsfromindia.com/storage/portfolios/portfolios-63eca36046e54.jpg",
    },
    {
      name: "Event Album",
      img: "https://admin.editsfromindia.com/storage/portfolios/portfolios-63e696f8c93e1.jpg",
    },
    {
      name: "Product Album",
      img: "https://admin.editsfromindia.com/storage/portfolios/portfolios-63f1d1cc0ba48.jpg",
    },
  ];

const Portfolio = () => {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="container py-5 my-5">
        <h4 className="blue-header">Photo Editing</h4>
        <Tabs
          defaultActiveKey="all"
          id="fill-tab-example"
          className="my-5 tabs-container"
          fill
        >
          <Tab eventKey="all" title="All">
            <div className="row row-cols-2 row-cols-md-3 row-cols-lg-4 g-4">
              {photoEditingCards.map((c) => (
                <div className="col">
                  <div className="shadow text-center p-2 rounded">
                    <img src={c.img} alt="" className="video-img" />
                    <p className="fw-bold py-1">{c.name}</p>
                  </div>
                </div>
              ))}
            </div>
          </Tab>
          <Tab eventKey="backgroundRemoval" title="Background Removal">
            <div className="row row-cols-2 row-cols-md-3 row-cols-lg-4 g-4">
              <div className="col">
                <div className="shadow text-center p-2 rounded">
                  <img
                    src="https://admin.editsfromindia.com/storage/portfolios/portfolios-63dc8de08122c.jpg"
                    alt=""
                    className="video-img"
                  />
                  <p className="fw-bold py-1">Background Removal</p>
                </div>
              </div>
            </div>
          </Tab>
          <Tab eventKey="clippingPath" title="Clipping Path">
            <div className="row row-cols-2 row-cols-md-3 row-cols-lg-4 g-4">
              <div className="col">
                <div className="shadow text-center p-2 rounded">
                  <img
                    src="https://admin.editsfromindia.com/storage/portfolios/portfolios-63dc9036961ac.jpg"
                    alt=""
                    className="video-img"
                  />
                  <p className="fw-bold py-1">Cliping Path</p>
                </div>
              </div>
            </div>
          </Tab>
          <Tab eventKey="imageMasking" title="Image Masking">
            <div className="row row-cols-2 row-cols-md-3 row-cols-lg-4 g-4">
              <div className="col">
                <div className="shadow text-center p-2 rounded">
                  <img
                    src="https://admin.editsfromindia.com/storage/portfolios/portfolios-63dc8f7b95035.jpg"
                    alt=""
                    className="video-img"
                  />
                  <p className="fw-bold py-1">Image Masking</p>
                </div>
              </div>
            </div>
          </Tab>
          <Tab eventKey="dropShadow" title="Drop Shadow">
            <div className="row row-cols-2 row-cols-md-3 row-cols-lg-4 g-4">
              <div className="col">
                <div className="shadow text-center p-2 rounded">
                  <img
                    src="https://admin.editsfromindia.com/storage/portfolios/portfolios-63dc8f184ba3d.jpg"
                    alt=""
                    className="video-img"
                  />
                  <p className="fw-bold py-1">Drop Shadow</p>
                </div>
              </div>
            </div>
          </Tab>
          <Tab eventKey="photoRetouching" title="Photo Retouching">
          <div className="row row-cols-2 row-cols-md-3 row-cols-lg-4 g-4">
              <div className="col">
                <div className="shadow text-center p-2 rounded">
                  <img
                    src="https://admin.editsfromindia.com/storage/portfolios/portfolios-63dc9036961ac.jpg"
                    alt=""
                    className="video-img"
                  />
                  <p className="fw-bold py-1">Photo Retouching</p>
                </div>
              </div>
            </div>
          </Tab>
        </Tabs>
        <h4 className="blue-header mt-5">Video Editing</h4>
        <Carousel
          swipeable={false}
          draggable={false}
          showDots={true}
          responsive={responsive}
          className="py-5"
        >
          {videoEditingCards.map((c) => (
            <div className="text-center card mx-1">
              <img src={c.img} alt="" className="video-img"/>
              <h5 className="fw-bold py-2">{c.name}</h5>
            </div>
          ))}
        </Carousel>
        <h4 className="blue-header mt-5">Album Editing</h4>
        <Tabs
          defaultActiveKey="all"
          id="fill-tab-example"
          className="my-5 tabs-container"
          fill
        >
          <Tab eventKey="all" title="All">
            <div className="row row-cols-2 row-cols-md-3 row-cols-lg-4 g-4">
              {aldumEditingCards.map((c) => (
                <div className="col">
                  <div className="ae-card shadow text-center p-2 rounded">
                    <img src={c.img} alt="" className="img-fluid" />
                    <p className="fw-bold py-1">{c.name}</p>
                  </div>
                </div>
              ))}
            </div>
          </Tab>
          <Tab eventKey="modelAlbum" title="Model Album">
            <div className="row row-cols-2 row-cols-md-3 row-cols-lg-4 g-4">
              <div className="col">
                <div className="ae-card shadow text-center p-2 rounded">
                  <img
                    src="https://admin.editsfromindia.com/storage/portfolios/portfolios-63eca36046e54.jpg"
                    alt=""
                    className="img-fluid"
                  />
                  <p className="fw-bold py-1">Model Album</p>
                </div>
              </div>
            </div>
          </Tab>
          <Tab eventKey="eventAlbum" title="Event Album">
            <div className="row row-cols-2 row-cols-md-3 row-cols-lg-4 g-4">
              <div className="col">
                <div className="ae-card shadow text-center p-2 rounded">
                  <img
                    src="https://admin.editsfromindia.com/storage/portfolios/portfolios-63e696f8c93e1.jpg"
                    alt=""
                    className="img-fluid"
                  />
                  <p className="fw-bold py-1">Model Album</p>
                </div>
              </div>
            </div>
          </Tab>
          <Tab eventKey="productAlbum" title="Product Album">
            <div className="row row-cols-2 row-cols-md-3 row-cols-lg-4 g-4">
              <div className="col">
                <div className="ae-card shadow text-center p-2 rounded">
                  <img
                    src="https://admin.editsfromindia.com/storage/portfolios/portfolios-63f1d1cc0ba48.jpg"
                    alt=""
                    className="img-fluid"
                  />
                  <p className="fw-bold py-1">Product Album</p>
                </div>
              </div>
            </div>
          </Tab>
        </Tabs>
      </section>
    </>
  );
};

export default Portfolio;
